In [1]:
import pandas as pd
import numpy as np
import tabula
from matplotlib import pyplot as plt

# Notas de Medicina - UERJ

## Importando os dados de arquivos pdf:

In [ ]:
df  = tabula.read_pdf("A-B.pdf", pages = "all")
df2 = tabula.read_pdf("C-F.pdf", pages = '2-86')
df3 = tabula.read_pdf("G-I.pdf", pages = "2-80")
df4 = tabula.read_pdf("J-K.pdf", pages = "2-64")
df5 = tabula.read_pdf("L.pdf", pages = "2-73")
df6 = tabula.read_pdf("M-O.pdf", pages = "2-90")
df7 = tabula.read_pdf("P-S.pdf", pages = "2-72")
df8 = tabula.read_pdf("T-Z.pdf", pages = "2-56")

In [ ]:
df

In [136]:
df3.rename(columns={'Nome do Candidato L.EST':'Nome do Candidato'}, inplace=True)
del df3['Unnamed: 2']

In [137]:
df_i2 = df.append(df2,ignore_index = True)
df_i3 = df_i2.append(df3,ignore_index = True)
df_i4 = df_i3.append(df4,ignore_index = True)
df_i5 = df_i4.append(df5,ignore_index = True)
df_i6 = df_i5.append(df6,ignore_index = True)
df_i7 = df_i6.append(df7,ignore_index = True)
df_final = df_i7.append(df8,ignore_index = True)

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pandas/core/frame.py:6211: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort)

In [138]:
df_final

,BIO,FIS,GEO,HIS,Inscrição,L.EST,LPL,MAT,Nome do Candidato,QUI,RED
0,"8,00",NaN,NaN,NaN,193005401-0,NaN,NaN,NaN,AARON JORGE MENDONCA SANTOS,"5,50","14,00"
1,NaN,NaN,NaN,FALTA,193037124-0,NaN,NaN,FALTA,AARON LUIZ XAVIER MENDONCA,NaN,FALTA
2,"4,75",NaN,NaN,NaN,193014263-9,NaN,NaN,NaN,ABEL BARROS QUADROS,"0,50","12,00"
3,NaN,NaN,NaN,"10,50",193022623-5,NaN,"1,00",NaN,ABEL HENRIQUE DA CONCEICAO SANTOS,NaN,"14,00"
4,NaN,"20,00",NaN,NaN,193006051-4,NaN,NaN,"16,00",ABIAS LINS PALHEIROS VIDAL,NaN,"12,00"
5,NaN,NaN,NaN,"3,25",193002686-0,NaN,"2,50",NaN,ABIGAIL ALVES GOMES FERNANDES,NaN,"14,00"
6,"15,25",NaN,NaN,NaN,193003211-3,NaN,NaN,NaN,ABNER FERREIRA MARTINS,"16,75","16,00"
7,NaN,NaN,NaN,"17,75",193020190-8,NaN,"7,75",NaN,ABNER LEANDRO DIAS DOS SANTOS,NaN,"12,00"
8,NaN,"0,25",NaN,NaN,193035003-9,NaN,NaN,"3,75",ABNER LOBATO DE AZEVEDO,NaN,"10,00"
9,NaN,NaN,"11,50",NaN,193022887-8,"4,00",NaN,NaN,ABRAAO CALEBE DE SOUZA FERREIRA,NaN,"10,00"
10,NaN,"19,25",NaN,NaN,193023518-2,NaN,NaN,"13,25",ABRAAO SALIM CALINOSK,NaN,"14,00"
11,"10,50",NaN,NaN,NaN,193013773-0,NaN,NaN,NaN,ABRAHAO LIMA VIDAL,"5,00","11,00"
12,NaN,NaN,NaN,NaN,193017752-3,"16,50","8,50",NaN,ACAUA AETE DA SILVA POZINO,NaN,"16,00"
13,NaN,NaN,NaN,"15,50",193005626-1,NaN,"2,00",NaN,ACOFA MOLINI NEPOMUCENO,NaN,"10,00"
14,"9,25",NaN,NaN,NaN,193005461-6,NaN,NaN,NaN,ACUCENA PUCU PINTO,"9,25","16,00"
15,NaN,NaN,NaN,"4,75",193013482-0,NaN,"1,75",NaN,ADAILTON DOS SANTOS JUNIOR,NaN,"8,00"
16,NaN,NaN,NaN,"14,50",193013796-8,NaN,"9,25",NaN,ADALBERTO BLANCO GONCALVES JUNIOR,NaN,"16,00"
17,"11,00",NaN,NaN,NaN,193006667-6,NaN,NaN,NaN,ADALBERTO CARDOSO PASSOS,"12,75","14,00"
18,NaN,NaN,"15,00",NaN,193022170-4,"11,25",NaN,NaN,ADAM LESLIE PHILLIPS GILL,NaN,"14,00"
19,NaN,NaN,NaN,NaN,193024553-6,NaN,NaN,"7,75",ADAURY ALHEIRO DA SILVA JUNIOR,"7,25","8,00"
20,NaN,NaN,NaN,NaN,193019958-2,"15,25","6,25",NaN,ADDA MOREIRA DA FONSECA DE MEIRELLES,NaN,"13,00"
21,NaN,NaN,NaN,"5,75",193023029-5,NaN,NaN,"0,00",ADDSON DE SANTANA SEVERO,NaN,"8,00"
22,NaN,"9,00",NaN,NaN,193014963-9,NaN,NaN,"12,50",ADEILSON DOS SANTOS MENDES JUNIOR,NaN,"12,00"
23,"7,75",NaN,NaN,NaN,193020950-4,NaN,NaN,NaN,ADEILTON PEDRO DE ALCANTARA,"6,50","14,00"
24,"14,25",NaN,NaN,NaN,193001232-9,NaN,NaN,NaN,ADELE THAIS ARAUJO CORREA DO NASCIMENTO,"12,00","12,00"
25,NaN,NaN,NaN,"8,50",193036192-4,NaN,"5,00",NaN,ADELIA CRUZ DE ALMEIDA PEREIRA,NaN,"10,00"
26,NaN,"2,25",NaN,NaN,193036282-3,NaN,NaN,"3,50",ADELINE MARQUES REIS,NaN,"12,00"
27,NaN,FALTA,NaN,NaN,193023061-4,NaN,NaN,FALTA,ADELINO FONTOURA NETO,NaN,FALTA
28,NaN,NaN,NaN,"11,75",193017023-2,NaN,NaN,"8,50",ADELSON DOS SANTOS ANTUNES,NaN,"14,00"
29,"4,75",NaN,NaN,NaN,193033727-0,"12,00",NaN,NaN,ADELSON SOUZA DOS SANTOS,NaN,"15,00"
...,...,...,...,...,...,...,...,...,...,...,...
30174,NaN,NaN,NaN,"16,00",193017572-5,NaN,"7,75",NaN,YURI MACEDO ROMERO DE SOUZA,NaN,"16,00"
30175,"9,25",NaN,NaN,NaN,193002739-0,NaN,NaN,NaN,YURI MARTINS DE MENEZES,"7,50","15,00"
30176,NaN,NaN,"10,25","12,00",193011125-1,NaN,NaN,NaN,YURI MARTINS DOS SANTOS,NaN,"16,00"
30177,NaN,NaN,NaN,"12,75",193008403-1,NaN,"10,75",NaN,YURI MARTINS GONCALVES DE QUEIROZ,NaN,"16,00"
30178,NaN,NaN,NaN,"14,00",193034308-9,NaN,"8,00",NaN,YURI MEIER DE AQUINO SILVA,NaN,"11,00"
30179,NaN,"8,25",NaN,NaN,193016953-6,NaN,NaN,"6,25",YURI MESQUITA PORTO,NaN,"12,00"
30180,NaN,"4,00",NaN,NaN,193017886-3,NaN,NaN,"11,75",YURI NOGUEIRA MOREIRA DA SILVA,NaN,"12,00"
30181,NaN,NaN,NaN,"12,75",193012445-2,NaN,"4,75",NaN,YURI NOGUEIRA REZENDE FERNANDES MAGALHAES,NaN,"8,00"
30182,"7,00",NaN,NaN,NaN,193022851-4,"9,50",NaN,NaN,YURI PEREIRA ANTUNES VIEIRA,NaN,"13,00"
30183,NaN,"8,25",NaN,NaN,193033460-0,NaN,NaN,"12,50",YURI PEREIRA GOMES,NaN,"10,00"
30184,"6,50",NaN,NaN,NaN,193031542-4,NaN,NaN,NaN,YURI RANIERI DE MEDEIROS CAMARGO,"9,50","8,00"
30185,NaN,NaN,NaN,"15,75",193022455-1,"14,25",NaN,NaN,YURI RICARDO GOCALVES DE MARIO BUENO,NaN,"12,00"
30186,NaN,FALTA,NaN,NaN,193011936-4,NaN,NaN,FALTA,YURI ROCHA DE LIMA,NaN,FALTA
30187,NaN,NaN,NaN,"17,50",193018402-8,NaN,"14,00",NaN,YURI SANTOS FLORENZANO COSCARELLI,NaN,"16,00"
30188,NaN,NaN,NaN,"13,00",193018092-6,NaN,"4,25",NaN,YURI SANTOS LIRIO SILVA,NaN,"12,00"
30189,NaN,NaN,NaN,"11,75",193018468-4,"7,00",NaN,NaN,YURI SOARES DE OLIVEIRA,NaN,"9,00"
30190,NaN,NaN,NaN,"14,75",193010346-6,NaN,NaN,"4,00",YURI SOUZA DE ARAUJO,NaN,"12,00"
30191,"7,25",NaN,NaN,NaN,193015717-0,NaN,NaN,NaN,YURI TAQUES HAIDAR,"8,25","14,00"
30192,NaN,NaN,FALTA,NaN,193018950-9,FALTA,NaN,NaN,YURI TRAVASSOS DOS SANTOS,NaN,FALTA
30193,"10,50",NaN,NaN,NaN,193025609-1,NaN,NaN,NaN,YURI VIANNA FERNANDES DA SILVA,"11,00","16,00"
30194,NaN,"18,00",NaN,NaN,193006668-8,NaN,NaN,"19,00",YURI VITAL CHALFUN DE MATOS AVILA DA SILVEIRA,NaN,"14,00"
30195,"8,00",NaN,NaN,NaN,193031060-2,NaN,NaN,NaN,YURI YUKIO DE SA KIMURA,"8,75","13,00"
30196,NaN,FALTA,NaN,NaN,193013744-0,NaN,NaN,FALTA,YVE SANTANA DE ALMEIDA,NaN,FALTA
30197,"15,75",NaN,NaN,NaN,193003482-1,NaN,NaN,NaN,YVIA MARIA SALGADO GOMES,"9,75","14,00"
30198,NaN,NaN,NaN,FALTA,193027866-0,NaN,FALTA,NaN,ZAIRA HELENA OLIVEIRA DE LUCENA,NaN,FALTA
30199,NaN,NaN,NaN,"12,25",193022102-1,NaN,"2,50",NaN,ZANDER DA SILVA LIMA,NaN,"12,00"
30200,NaN,NaN,"5,50","5,25",193003246-5,NaN,NaN,NaN,ZENEIDA DUARTE BELO,NaN,"11,00"
30201,NaN,NaN,NaN,"11,50",193000449-3,NaN,"11,50",NaN,ZILAH PAES AIRES BARBOSA,NaN,"14,00"
30202,NaN,"16,00",NaN,NaN,193025177-4,NaN,NaN,"20,00",ZOWIE SILVA VAN EMMERIK,NaN,"13,00"
30203,NaN,NaN,NaN,"9,50",193022139-7,NaN,"4,75",NaN,ZYGMUNT RAYMOND SULISTROWSKI,NaN,"10,00"

## Filtrando candidatos que fizeram Biologia e Química:

In [161]:
l_candidato = []
for i in range(len(df_final)):
    if type(df_final['BIO'][i]) != float and type(df_final['QUI'][i]) != float:
        if df_final['BIO'][i] != 'FALTA' and df_final['BIO'][i] != 'BIO':
            if df_final['QUI'][i] != 'FALTA' and df_final['QUI'][i] != 'QUI':
                l_candidato.append(i)

In [174]:
candidatos = df_final.iloc[l_candidato, [0,8,9,10]]

In [175]:
candidatos

         BIO                          Nome do Candidato    QUI    RED
0       8,00                AARON JORGE MENDONCA SANTOS   5,50  14,00
2       4,75                        ABEL BARROS QUADROS   0,50  12,00
6      15,25                     ABNER FERREIRA MARTINS  16,75  16,00
11     10,50                         ABRAHAO LIMA VIDAL   5,00  11,00
14      9,25                         ACUCENA PUCU PINTO   9,25  16,00
17     11,00                   ADALBERTO CARDOSO PASSOS  12,75  14,00
23      7,75                ADEILTON PEDRO DE ALCANTARA   6,50  14,00
24     14,25    ADELE THAIS ARAUJO CORREA DO NASCIMENTO  12,00  12,00
34      1,25                   ADIONE FARIAS DOS SANTOS   0,50   0,00
37     11,50                       ADRIAN ARAUJO MENDES  13,25  12,00
39     17,25                   ADRIAN CARVALHO VILLARDI  17,50  14,00
40      1,00                    ADRIAN DE SOUZA MARTINS   0,50  10,00
49     17,50                        ADRIANA FIUZA ALVES  16,50  17,00
54      5,50                  ADRIANA PERDIGAO DOS REIS   2,75  10,00
55     10,50  ADRIANA RAPOSO LAMORI FERREIRA DE AZEVEDO  11,00  15,00
58     11,25         ADRIANE CRISTINA MATTOS DE MIRANDA  11,75  14,00
66      3,25                  ADRIANE PEREIRA MEIRELLES   6,00  12,00
68      6,00                     ADRIANE SILVA BARCELOS   4,50  14,00
69      8,25          ADRIANNY ANGELICA ALMEIDA PEREIRA  10,00  12,00
73     12,75                    ADRIANO CORREA CORDEIRO  12,25  14,00
81      3,75                      ADRIANO SILVA PEREIRA   1,50  12,00
83      4,00            ADRIANY BRASIL FIRMINO DA SILVA   6,50  12,00
86     15,00                       ADRIEL FESTER DUARTE  16,75   8,00
95      5,75         ADRIELLE CRISTINA MIRANDA DA SILVA   6,75  12,00
99     10,50                     ADRIELLY DA COSTA MORO  11,25  15,00
100     4,25                   ADRIELLY DA SILVA DUARTE   5,50  14,00
101     3,75                  ADRIELLY DE AMORIM CHAVES   2,75  12,00
102    13,75             ADRIELLY MEDEIROS DE ALCANTARA  13,25  16,00
104     3,50                        ADRIELY COSTA RAMOS   4,75  12,00
105     2,50               ADRIELY GONCALVES DE ALMEIDA   1,75  12,00
...      ...                                        ...    ...    ...
30102  13,25          YASMINN FREITAS MEIRELES FERREIRA  17,25  12,00
30103  10,50                           YASMYN FERNANDES   6,75  12,00
30110   4,75               YGOR DE ALMEIDA VEGELE SOUSA   6,75  10,00
30111   5,50               YGOR DE LIMA PINTAS FERREIRA   1,75  10,00
30115  13,50      YGOR MONTEIRO ALMEIDA SOARES DA ROCHA   8,25  14,00
30118   0,00          YNGRID AVELINO FRANCISCO DA SILVA   0,50   4,00
30120   5,00         YNGRID CARVALHO PORTELA DOS SANTOS   4,00  12,00
30121   8,50               YNGRID MARQUES DO COUTO LIMA   4,50  12,00
30122   8,50              YNGRID MORAES FERREIRA PASSOS  10,00  16,00
30123   6,00          YOHANA ANDRESSA VALENTIM DE SOUZA   6,25  10,00
30125  11,75             YOLAN FERNANDES DA SILVA FILHO   6,75  14,00
30127  12,75                     YOLANDA MARIA TEIXEIRA  12,25  12,00
30128  16,00                        YONE PINTO DA SILVA  14,50  16,00
30130   3,50             YRIS ISABELE DOS SANTOS COELHO   3,50  12,00
30140   3,00                   YURI BARBOSA DE OLIVEIRA   0,50  10,00
30144  10,25         YURI CASSIANO DE OLIVEIRA DA SILVA  10,50  12,00
30146  13,25                YURI CHAGAS FIGUEIRO FRANCA  15,75  16,00
30147  11,00      YURI CHAVES ALVES FELIPPE DE OLIVEIRA  10,00  16,00
30148  14,75                      YURI CORDEIRO FONSECA  12,00  12,00
30154   8,50                      YURI DE ALMEIDA KOPKE   8,25  14,00
30159   9,75                           YURI FELIX PEDRA   8,00  10,00
30161   8,25                 YURI GABRIEL SOARES CAMPOS  10,25  16,00
30167   6,75                    YURI LEANDRO DOS SANTOS   2,25  12,00
30171   6,00             YURI LOPES RIBEIRO GARCIA DIAS   0,75  12,00
30175   9,25                    YURI MARTINS DE MENEZES   7,50  15,00
30184   6,50           YURI RANIERI DE MEDEIROS CAMARGO   9,50   8,00
30191   7,25                         YURI TAQUES HAIDAR   8,25  14,00
30193  10,50             YURI VIANNA FERNANDES DA SILVA  11,00  16,00
30195   8,00                    YURI YUKIO DE SA KIMURA   8,75  13,00
30197  15,75                   YVIA MARIA SALGADO GOMES   9,75  14,00

[10497 rows x 4 columns]

## Limpando valores numéricos e obtendo formato final:

In [194]:
bio = []
qui = []
red = []
nome = []

for i in l_candidato:
    bio.append(float(candidatos['BIO'][i].replace(',', ".")))
    qui.append(float(candidatos['QUI'][i].replace(',', ".")))
    red.append(float(candidatos['RED'][i].replace(',', ".")))
    nome.append(candidatos['Nome do Candidato'][i])
    
dict1 = { 'candidato': nome,'biologia': bio, 'quimica': qui, 'redação': red}

In [195]:
notas1 = pd.DataFrame(dict1)

In [209]:
nfinal = []
for i in range(len(notas1)):
    nota_final = notas1['biologia'][i]*2 + notas1['redação'][i] + notas1['quimica'][i] + 20.0
    nfinal.append(nota_final)
    
dict2 = { 'candidato': nome,'biologia': bio, 'quimica': qui, 'redação': red, 'nota final': nfinal}

In [210]:
notas = pd.DataFrame(dict2)

In [220]:
final_final = notas.sort_values(by='nota final', ascending = False)
final_final = final_final.reset_index()
del final_final['index']

In [221]:
final_final

,candidato,biologia,quimica,redação,nota final
0,ANA CAROLINA RODRIGUES LADO,20.00,20.00,18.0,98.00
1,CAIO MEDEIROS FERNANDES,19.50,19.25,17.0,95.25
2,GABRIELA TEIXEIRA PEIXOTO,19.00,20.00,17.0,95.00
3,LAURA SOARES VILAS BOAS,20.00,15.00,20.0,95.00
4,GABRIELA GRIECO SABIONI,18.75,19.50,18.0,95.00
5,ANNA CLARA MARTINIANO DA COSTA,19.50,20.00,16.0,95.00
6,BEATRIZ CUNTA GONCALVES,19.50,18.75,17.0,94.75
7,LETICCIA MESQUITA ESTEVES,20.00,18.50,16.0,94.50
8,TABATA DA CUNHA ESTEVES DE ALMEIDA,20.00,18.25,16.0,94.25
9,LAURA ZALCBERG RENAULT,19.00,20.00,16.0,94.00
10,VITORIA EL WARRAK,19.00,20.00,16.0,94.00
11,VANESSA BEZERRA NUNES,20.00,20.00,14.0,94.00
12,JULIA CHAVES CORDOVIL,19.00,19.00,17.0,94.00
13,LAYLA VITORIA DE SOUZA BERNARDINO,19.25,17.25,18.0,93.75
14,ANA LUIZA BARREIRA LINS,19.50,17.75,17.0,93.75
15,FERNANDO COSTA VIEITAS,18.50,18.75,18.0,93.75
16,MARIA EDUARDA ARAGAO COSTA,19.50,17.50,17.0,93.50
17,HUMBERTO BERTOLA SIQUEIRA DE ALMEIDA,19.00,19.25,16.0,93.25
18,PIETRA ALCANTARA GOMES REIS DE SOUZA,19.00,18.25,17.0,93.25
19,CLARA MARTINS ROLLEMBERG DE SOUZA,19.50,20.00,14.0,93.00
20,PEDRO RENATO DE MORAES TRAVASSOS,19.25,18.50,16.0,93.00
21,PEDRO ERNANDES BERGAMO,18.50,19.00,17.0,93.00
22,DAVID CURI BARBOSA IZOTON,19.00,19.00,16.0,93.00
23,PEDRO ABIB LIMA LEAL,19.50,17.75,16.0,92.75
24,BERNARDO JOSE DE ABREU OLIVEIRA SACRAMENTO,18.00,18.50,18.0,92.50
25,ANA LUISA AGOSTINHO MARQUES DOS SANTOS,18.00,19.50,17.0,92.50
26,MAIRA PEDROSA DE PAULA GUIMARAES,19.25,20.00,14.0,92.50
27,MYLENA DALVI CALABREZ,18.00,19.50,17.0,92.50
28,BRUNA ZANGEROLAME DE CARVALHO,20.00,16.50,16.0,92.50
29,RUAN DA SILVEIRA VIANA,19.50,17.50,16.0,92.50
...,...,...,...,...,...
10467,KAROLLINE GARCIA DE OLIVEIRA,2.25,2.00,1.0,27.50
10468,MANUELLE RIBEIRO BRAGANCA,2.75,1.50,0.0,27.00
10469,ARTHUR HENRICI SOUZA DE ASSIS,0.50,0.00,6.0,27.00
10470,ANA CAROLINA NASCIMENTO DA COSTA,1.75,3.25,0.0,26.75
10471,EDUARDA CRISTINA DOS SANTOS FERREIRA,1.00,0.50,4.0,26.50
10472,ALESSANDRA FROES PEREIRA DA SILVA,1.00,0.50,4.0,26.50
10473,MARIA EDUARDA ALEXANDRINO ALVES,0.75,4.75,0.0,26.25
10474,LETICIA FERREIRA DO NASCIMENTO,0.00,0.00,6.0,26.00
10475,DAYANA CANEDO AMORIM DA SILVA,0.50,0.75,4.0,25.75
10476,LOHAYNE DINIZ GENOVEZ DE MORAES,0.50,0.50,4.0,25.50
10477,CARLA RAFAELA LOPES DA SILVA,2.50,0.50,0.0,25.50
10478,DANIEL ALEXANDRE OLIVEIRA NUNES DA SILVA,1.50,2.25,0.0,25.25
10479,GIULLIA WERNECK PESSANHA DE CARVALHO,1.50,2.00,0.0,25.00
10480,CHARLES JORDAN JUNIOR,0.50,0.00,4.0,25.00
10481,IGOR GABRIEL DOUETTS GOULART,2.50,0.00,0.0,25.00
10482,YNGRID AVELINO FRANCISCO DA SILVA,0.00,0.50,4.0,24.50
10483,APARECIDA LUIZ DA SILVA,0.00,0.00,4.0,24.00
10484,TAYNA MARTINS DA SILVA,0.00,0.00,4.0,24.00
10485,MARIA CLARA RIBAS CORREA,2.00,0.00,0.0,24.00
10486,CATHERINE PIMENTEL CARVALHO DE AZEVEDO,1.50,0.00,0.0,23.00
10487,LUCAS FERNANDES CAMPOS,1.00,1.00,0.0,23.00
10488,ADIONE FARIAS DOS SANTOS,1.25,0.50,0.0,23.00
10489,MARIA EDUARDA CARUSO DEVOLDER,0.00,2.50,0.0,22.50
10490,MATHEUS SIQUEIRA DE ASSIS MADUREIRA,0.50,1.00,0.0,22.00
10491,MATHEUS HENRIQUE MENEZES DA COSTA,0.50,0.00,0.0,21.00
10492,LESLIN DE MEDEIROS LISBOA,0.00,0.50,0.0,20.50
10493,AMANDA CHRISTINA DE OLIVEIRA,0.00,0.00,0.0,20.00
10494,JESSICA SOUZA DE OLIVEIRA,0.00,0.00,0.0,20.00
10495,GABRIELLA SEARA DE ANDRADE,0.00,0.00,0.0,20.00
10496,MALU PANIZZI DE PODESTA,0.00,0.00,0.0,20.00